package seedstonemod;

import net.minecraftforge.fml.common.ModMetadata;

public class ModInfo
{
	public static void loadInfo(ModMetadata meta)
	{
		meta.version = SeedstoneMod.VERSION;
		meta.autogenerated = false;
	}
}
